### PR TITLE
only add -g for javac invocations.

### LINKED ISSUE #1512: Universally adding '-g' to the compiler invocation breaks kotlin scripts
kotlinc doesn't support a `-g` flag so kotlin scripts can't be compiled.

### PR DESCRIPTION
**Pull request by evanchooly**
Only add -g for javac invocations so kotlin scripts can be compiled.

fixes #1512

### CODE REVIEW

**Review by quintesse — CHANGES_REQUESTED** [review]
Hi @evanchooly , great try, but unfortunately that's not the way to fix it 🙂 
If you want to improve it you're more than welcome!
The actual change, which I should have implemented in the first place, should be made here: https://github.com/jbangdev/jbang/blob/main/src/main/java/dev/jbang/source/sources/JavaSource.java#L30
(you can take a look at this as an example of how: https://github.com/jbangdev/jbang/blob/main/src/main/java/dev/jbang/source/sources/GroovySource.java#L39-L41)

**Comment by quintesse** [comment]
Also, if you could add a test, similar to this one: https://github.com/jbangdev/jbang/blob/main/src/test/java/dev/jbang/source/TestBuilder.java#L32-L50 , where you assert that a "-g" does **not** exist for Kotlin, I would be eternally grateful 🙂

**Comment by evanchooly** [comment]
done.  that should be closer to correct.

**Review by quintesse — APPROVED** [review]

**Comment by quintesse** [comment]
Merged. Thanks for your patch @evanchooly !

**Pull request merged**
