### PR TITLE
docs: Update organizing.adoc

### PR DESCRIPTION
**Pull request by k-klemmer**
Description: suggestion to make a section in `File Organization` more readable.

### CODE REVIEW

**Review by quintesse — APPROVED** [review]
LGTM

**Review by quintesse — CHANGES_REQUESTED** [review]
Well, I said LGTM but I forgot that we require commits descriptions to follow semantic commit rules. Could you reword your commit description to start with "docs: " and repush? Thanks!

**Comment by quintesse** [comment]
Actually it's "docs: ", plural :-)

**Review by quintesse — APPROVED** [review]

**Comment by quintesse** [comment]
Thanks @k-klemmer !

**Review by maxandersen — APPROVED** [review]

**Review by maxandersen — APPROVED** [review]

**Pull request merged**
