### PR TITLE
fix: `info tools` now downloads JDKs again

### LINKED ISSUE #1569: Make `info tools` download JDKs again
After a heated discussion it was decided to again download JDKs when using `info tools`

### PR DESCRIPTION
**Pull request by quintesse**
Fixes #1569

### CODE REVIEW

**Comment by maxandersen** [comment]
If I have a file with `//JAVA 9` then `jbang info tools t.java` returns jdk as Java 11 rather than Java 9.

`jbang build t.java` actually downloads java 9 - so there seem to be some mismatch?

**Comment by quintesse** [comment]
Are you sure @maxandersen ? I just tested and retested and it seems to work fine here.

**Comment by quintesse** [comment]
And if you're sure I'd need many more details. What is your current JDK, what does `t.java` look like. What JDKs do you have installed. The verbose output of the `info tools` command , etc.

**Comment by quintesse** [comment]
Btw, check if your Java 9 install completed correctly, I just noticed that the Java 9 package has a different structure from the rest and Jbang is not handling it well.

**Comment by quintesse** [comment]
Added a fix for that as a bonus

**Comment by maxandersen** [comment]
t.java:
```
///usr/bin/env jbang "$0" "$@" ; exit $?
//JAVA 9

import static java.lang.System.*;

public class t {

    public static void main(String... args) {
        out.println("Hello World");
    }
}
```

```
jbang info tools env@jbangdev
{
  "originalResource": "https://github.com/jbangdev/jbang-catalog/blob/HEAD/env.java",
  "backingResource": "/Users/manderse/.jbang/cache/urls/442987f5d8d5868e2de293586ebd129e5130b8f60c35cc9569d0bdd97041c12a/env.java",
  "applicationJar": "/Users/manderse/.jbang/cache/jars/env.java.a9698542287f63ccc8120cf14c41e464b3d015626675bbe06bcca02faaea47d1/env.jar",
  "dependencies": [
    "info.picocli:picocli:4.2.0",
    "de.vandermeer:asciitable:0.3.2",
    "org.jline:jline:3.16.0"
  ],
  "resolvedDependencies": [
    "/Users/manderse/.m2/repository/info/picocli/picocli/4.2.0/picocli-4.2.0.jar",
    "/Users/manderse/.m2/repository/de/vandermeer/asciitable/0.3.2/asciitable-0.3.2.jar",
    "/Users/manderse/.m2/repository/de/vandermeer/ascii-utf-themes/0.0.1/ascii-utf-themes-0.0.1.jar",
    "/Users/manderse/.m2/repository/de/vandermeer/skb-interfaces/0.0.1/skb-interfaces-0.0.1.jar",
    "/Users/manderse/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar",
    "/Users/manderse/.m2/repository/org/antlr/ST4/4.0.8/ST4-4.0.8.jar",
    "/Users/manderse/.m2/repository/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar",
    "/Users/manderse/.m2/repository/org/antlr/antlr4/4.5.1/antlr4-4.5.1.jar",
    "/Users/manderse/.m2/repository/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar",
    "/Users/manderse/.m2/repository/de/vandermeer/char-translation/0.0.2/char-translation-0.0.2.jar",
    "/Users/manderse/.m2/repository/org/jline/jline/3.16.0/jline-3.16.0.jar"
  ],
  "availableJdkPath": "/Users/manderse/.jbang/cache/jdks/11",
  "compileOptions": [
    "-g"
  ],
  "sources": [
    {
      "originalResource": "https://github.com/jbangdev/jbang-catalog/blob/HEAD/env.java",
      "backingResource": "/Users/manderse/.jbang/cache/urls/442987f5d8d5868e2de293586ebd129e5130b8f60c35cc9569d0bdd97041c12a/env.java"
    }
  ]
}
```

notice that is using java 11.

Unfortuantely I cannot reproduce this anymore. now it tries to download java 9.

Which then errors...even with that last fix in.

```
jbang info tools t.java
[jbang] Downloading JDK 9. Be patient, this can take several minutes...
[jbang] [ERROR] Required Java version not possible to download or install. You can run with '--java 11' to force using the default installed Java.
{
  "originalResource": "t.java",
  "backingResource": "/Users/manderse/code/jbangdev/jbang/t.java",
  "applicationJar": "/Users/manderse/.jbang/cache/jars/t.java.7fb7f0b4adc6b057b7e34e378c4bf0afea6208006d50439a36574f2600b609fc/t.jar",
  "resolvedDependencies": [],
  "javaVersion": "9",
  "requestedJavaVersion": "9",
  "compileOptions": [
    "-g"
  ],
  "sources": [
    {
      "originalResource": "t.java",
      "backingResource": "/Users/manderse/code/jbangdev/jbang/t.java"
    }
  ]
}
```

**Comment by quintesse** [comment]
Can you show the verbose output of that error? And show the contents of `~/.jbang/cache/jdks/9`?

**Comment by maxandersen** [comment]
ignore me - I autocompleted and got env@jbangdev instead of t.java so works as expected but fails on downloading java 9 for some reason.

**Comment by maxandersen** [comment]
actually - same error on //JAVA 10, 12 and 14. (as in anything I don have downloaded I try fails)

**Comment by maxandersen** [comment]
Java 18 worked - i'm on M1 - could it be that 9, 10, 12, and 14 aren't available to download?

**Comment by maxandersen** [comment]
verbose output:

```
 jbang info tools --verbose t.java
[jbang] [0:226] jbang version 0.103.2.3
[jbang] [0:246] Resolving resource ref: t.java
[jbang] [0:249] Resolved resource ref as: t.java (cached as: /Users/manderse/code/jbangdev/jbang/t.java)
[jbang] [0:263] Looking for JDK: 12
[jbang] [0:273] Using cached file /Users/manderse/.jbang/cache/urls/0f9fcd08469c09a7a7ee5571f6c1e8c7ac8d1a1bf9b1eb194dc10cc6eef22267/temurin for remote https://api.foojay.io/disco/v3.0/distributions/temurin?latest_per_update=true
[jbang] [0:276] Using cached file /Users/manderse/.jbang/cache/urls/c7513504fc9b7fb1fed8880e3f18d012d6a7f8d9e87864cb93a9132ab7c6d036/aoj for remote https://api.foojay.io/disco/v3.0/distributions/aoj?latest_per_update=true
[jbang] [0:281] Downloading JDK 12. Be patient, this can take several minutes...
[jbang] [0:282] Downloading https://api.foojay.io/disco/v3.0/directuris?distro=aoj&javafx_bundled=false&libc_type=libc&archive_type=tar.gz&operating_system=mac&package_type=jdk&version=12&architecture=aarch64&latest=available
[jbang] [0:363] Requesting HTTP GET https://api.foojay.io/disco/v3.0/directuris?distro=aoj&javafx_bundled=false&libc_type=libc&archive_type=tar.gz&operating_system=mac&package_type=jdk&version=12&architecture=aarch64&latest=available
[jbang] [0:363] Headers {User-Agent=[JBang/0.103.2.3 (Mac OS X/13.2.1/aarch64) Java/11.0.18/Eclipse Adoptium]}
[jbang] [1:669] Deleting folder /Users/manderse/.jbang/cache/urls/9dfa922157be7293758043f54a23afb7db7971ac92f564d363bc081622a740b0.tmp
[jbang] [1:673] [ERROR] Required Java version not possible to download or install. You can run with '--java 11' to force using the default installed Java.
{
  "originalResource": "t.java",
  "backingResource": "/Users/manderse/code/jbangdev/jbang/t.java",
  "applicationJar": "/Users/manderse/.jbang/cache/jars/t.java.05815161024f665cc0329c95979ca45ad51713fbd14002bafe40716173ac35c1/t.jar",
  "resolvedDependencies": [],
  "javaVersion": "12",
  "requestedJavaVersion": "12",
  "compileOptions": [
    "-g"
  ],
  "sources": [
    {
      "originalResource": "t.java",
      "backingResource": "/Users/manderse/code/jbangdev/jbang/t.java"
    }
  ]
}
```

**Comment by quintesse** [comment]
> Java 18 worked - i'm on M1 - could it be that 9, 10, 12, and 14 aren't available to download?

Ah yes, that's of course possible. Have you tried running `jbang jdk list --available`?

**Comment by maxandersen** [comment]
```
jbang jdk list --available
output= 8 (8.0.372-ea+3) 9 (9.0.4) 10 (10.0.2) 11 (11.0.19-ea+2) 12 (12.0.2) 13 (13.0.2) 14 (14.0.2) 15 (15.0.2) 16 (16.0.2+7) 17 (17.0.7-ea+2) 18 (18.0.2.1+1) 19 (19.0.2+7) 20 (20-ea+36)
   8 (8.0.372-ea+3)
   9 (9.0.4)
   10 (10.0.2)
   11 (11.0.19-ea+2)
   12 (12.0.2)
   13 (13.0.2)
   14 (14.0.2)
   15 (15.0.2)
   16 (16.0.2+7)
   17 (17.0.7-ea+2)
   18 (18.0.2.1+1)
   19 (19.0.2+7)
   20 (20-ea+36)
```

so...they should work..but does not?

**Comment by quintesse** [comment]
Can you run `jbang info tools --verbose t.java` again (with java set to 12 as before) and post the output again? (I need to see the cached version, not a new download)

**Comment by maxandersen** [comment]
```
jbang info tools --verbose t.java
[jbang] [0:220] jbang version 0.103.2.1
[jbang] [0:239] Resolving resource ref: t.java
[jbang] [0:241] Resolved resource ref as: t.java (cached as: /Users/manderse/code/jbangdev/jbang/t.java)
[jbang] [0:266] Using cached file /Users/manderse/.jbang/cache/urls/0f9fcd08469c09a7a7ee5571f6c1e8c7ac8d1a1bf9b1eb194dc10cc6eef22267/temurin for remote https://api.foojay.io/disco/v3.0/distributions/temurin?latest_per_update=true
[jbang] [0:270] Using cached file /Users/manderse/.jbang/cache/urls/c7513504fc9b7fb1fed8880e3f18d012d6a7f8d9e87864cb93a9132ab7c6d036/aoj for remote https://api.foojay.io/disco/v3.0/distributions/aoj?latest_per_update=true
{
  "originalResource": "t.java",
  "backingResource": "/Users/manderse/code/jbangdev/jbang/t.java",
  "applicationJar": "/Users/manderse/.jbang/cache/jars/t.java.05815161024f665cc0329c95979ca45ad51713fbd14002bafe40716173ac35c1/t.jar",
  "resolvedDependencies": [],
  "javaVersion": "12",
  "requestedJavaVersion": "12",
  "compileOptions": [
    "-g"
  ],
  "sources": [
    {
      "originalResource": "t.java",
      "backingResource": "/Users/manderse/code/jbangdev/jbang/t.java"
    }
  ]
}
```

**Comment by maxandersen** [comment]
if I do `jbang cache clear` and run info tools again I get:

```
 jbang info tools --verbose t.java
[jbang] [0:196] jbang version 0.103.2.1
[jbang] [0:216] Resolving resource ref: t.java
[jbang] [0:218] Resolved resource ref as: t.java (cached as: /Users/manderse/code/jbangdev/jbang/t.java)
[jbang] [0:330] Requesting HTTP GET https://api.foojay.io/disco/v3.0/distributions/temurin?latest_per_update=true
[jbang] [0:330] Headers {User-Agent=[JBang/0.103.2.1 (Mac OS X/13.2.1/aarch64) Java/11.0.18/Eclipse Adoptium]}
[jbang] [1:717] Downloaded file https://api.foojay.io/disco/v3.0/distributions/temurin?latest_per_update=true
[jbang] [1:722] Requesting HTTP GET https://api.foojay.io/disco/v3.0/distributions/aoj?latest_per_update=true
[jbang] [1:722] Headers {User-Agent=[JBang/0.103.2.1 (Mac OS X/13.2.1/aarch64) Java/11.0.18/Eclipse Adoptium]}
[jbang] [1:994] Downloaded file https://api.foojay.io/disco/v3.0/distributions/aoj?latest_per_update=true
{
  "originalResource": "t.java",
  "backingResource": "/Users/manderse/code/jbangdev/jbang/t.java",
  "applicationJar": "/Users/manderse/.jbang/cache/jars/t.java.05815161024f665cc0329c95979ca45ad51713fbd14002bafe40716173ac35c1/t.jar",
  "resolvedDependencies": [],
  "javaVersion": "12",
  "requestedJavaVersion": "12",
  "compileOptions": [
    "-g"
  ],
  "sources": [
    {
      "originalResource": "t.java",
      "backingResource": "/Users/manderse/code/jbangdev/jbang/t.java"
    }
  ]
}
```

**Comment by quintesse** [comment]
Ok, so the `jdk list --available` actually doesn't show what's available for your os/architecture, just whatever is available. That should definitely be fixed.

So for your os/arch there's only 11, 17, 18 and 19

**Comment by maxandersen** [comment]
okey so this pr specifically works. handling missing jdks would be separate issue. merging this then.

**Pull request merged**
