### PR TITLE
fix: jbang config set updates config key with updated value

### PR DESCRIPTION
**Pull request by grumpyf0x48**
fix: jbang config set updates config key with updated value (#1299)

### CODE REVIEW

**Comment by grumpyf0x48** [comment]
Use an intermediate `Properties` object when saving conf as it is already done in load.

Seems that using the initial object has side effects with cursor current position.

**Comment by quintesse** [comment]
@grumpyf0x48 I'm glad you tried to fix this but in fact the problem was in a dependency that had to be fixed upstream: https://github.com/codejive/java-properties/issues/6. When a new release with that fix gets published we can fix it here. Closing this PR.

**Comment by grumpyf0x48** [comment]
Sorry but it's not a try, the test validates it fixes the issue :-)

The question i had was why using another implementation of Properties ? It is not a common practice - especially in only one source file.

**Comment by quintesse** [comment]
It made the test pass, indeed :-)
But unfortunately the underlying issue was more severe so it had to be fixed upstream.

We're using that implementation of Properties because we had a requirement that any formatting and/or comments in the config files had to be maintained. The standard java Properties doesn't do that, you can put comments in a Properties file, but once you read it into memory all of that is gone. This implementation maintains all formatting and comments, which is what we wanted.

**Comment by grumpyf0x48** [comment]
Seen that limitation !

And clearly java.util.Properties probably won't be updated - it's a very old class of JDK.

**Comment by quintesse** [comment]
Hey look, in the end I used (part of) your test :-)

**Pull request closed without merging**
