### PR TITLE
Implemented all items from issue #854

### LINKED ISSUE #854: Make `catalog` commands more like `alias`
The two commands have "grown apart" somewhat:

- [x] Right now the `catalog add` command still requires 2 arguments, a name and a url or path, but `alias add` was changed to use an optional `--name` flag. We should do the same for `catalog add`.
- [x] `catalog list` doesn't have a `--show-origin` flag like `alias list` has. It would perhaps be nice if it did.
- [x] `catalog list` also doesn't have colored output
- [x] docs

### PR DESCRIPTION
**Pull request by quintesse**
Fixes #854

### CODE REVIEW

**Comment by maxandersen** [comment]
fails on windows so not merging yet.

**Review by maxandersen — CHANGES_REQUESTED** [review]
windows test issue should be fixed and readme.adoc refer to the old form so would be good to fix that too.

**Comment by maxandersen** [comment]
damn - wrong issue i commented on ;)

**Comment by quintesse** [comment]
CI passed

**Pull request merged**
