### PR TITLE
feat: better error handling for //FILES

### PR DESCRIPTION
**Pull request by maxandersen**
this PR introduces a better error handling when //FILES cannot resolve files

### CODE REVIEW

**Comment by maxandersen** [comment]
the number of files changed is just high as I added notion of description to resolvers to give some context.

Not 100% convinced we need to include it always (maybe only when --verbose?)

**Comment by maxandersen** [comment]
whoops - some tests not passing ...investigating

**Comment by maxandersen** [comment]
originally pr had "fix" to make **/*.java include root files but realized that is not right...if one wants that one uses **.java (no /).

which also makes the code much cleaner (zero changes needed for that :)

**Review by quintesse — DISMISSED** [review]
LGTM

**Comment by quintesse** [comment]
Good PR. The only thing I'm unsure about is this one:

> originally pr had "fix" to make **/*.java include root files but realized that is not right...if one wants that one uses **.java (no /).

Is that common behaviour? I always assumed that `**/` meant 0, 1 or more folders. So `**/*.java` would indeed include root items.

**Comment by maxandersen** [comment]
Its at least how globmatcher in the jdk behaves. And it kinda makes sense that \ means at least one directory. 

I thought same as you but I think I thought that as in traditional java you always have layers of dira :)

**Comment by quintesse** [comment]
> Its at least how globmatcher in the jdk behaves

Seems you are right. And it does make sense, but it seems it's different from other glob patterns I have used in the past.

Indeed, if I look at Gradle it says they follow Ant's globbing rules and looking at the Ant docs they do specifically state that `**/X` also matches `X`.

**Pull request merged**
