### PR TITLE
fix: Jbang won't print extra newline when no output was generated

### PR DESCRIPTION
**Pull request by quintesse**

### CODE REVIEW

**Comment by maxandersen** [comment]
can you add a test so we don't accidentally break this in future ?

**Comment by quintesse** [comment]
> can you add a test so we don't accidentally break this in future ?

Actually, I don't know how. It seems that Karate first strips the captured output before testing it, so even though the output contains a newline if I compare it with an empty string it still says it matches.

**Comment by quintesse** [comment]
Ok, test added!

**Comment by maxandersen** [comment]
thankayou!

**Pull request merged**
