### PR TITLE
feat: honor JBANG_DOWNLOAD_VERSION in bootstrap setup

### PR DESCRIPTION
**Pull request by maxandersen**
allows to do:

`curl -Ls https://sh.jbang.dev | JBANG_DOWNLOAD_VERSION=0.99.2 bash -s - app setup`

Similar for Windows but haven't tested it - thus marking this draft for now.

### CODE REVIEW

**Comment by maxandersen** [comment]
also added consistent printing of url if download fails.

**Comment by maxandersen** [comment]
rationale is to make it easy to do regression testing and not requiring having to fallback to use sdkman or similar as seen in #1504

**Review by quintesse — APPROVED** [review]
LGTM

**Comment by maxandersen** [comment]
Did you test it on windows? :)

**Comment by quintesse** [comment]
Testing is for wussies ;-)
Should work now.

**Comment by quintesse** [comment]
Btw, I don't how to do the same thing you showed in the issue description on Windows. There's no way on Windows (AFAIK) to set a variable and run a command at the same time, so you'd need to run two separate commands.

**Comment by maxandersen** [comment]
Yes. Env setup on windows requires seperate step.

**Pull request merged**
