### PR TITLE
feat: enable integrations to run externally

### LINKED ISSUE #1084: jbang --java 17 when default is java 11 build integration fails
**Describe the bug**
Have java 11 in system path.
Run `jbang --java 17 https://gist.github.com/rivasdiaz/f2e9efd1bf2079f0101f865846af2502` and you get error about 

```
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ConfigBuildStep#generateConfigClasses threw an exception: java.lang.UnsupportedClassVersionError: MavenStatsConfig has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:445)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:405)
        at io.quarkus.deployment.configuration.ConfigMappingUtils.toClass(ConfigMappingUtils.java:93)
        at io.quarkus.deployment.configuration.ConfigMappingUtils.generateConfigClasses(ConfigMappingUtils.java:51)
```

as if it compiles with java 17 but then falls back to running quarkus build integration with java 11...

solution would be to run that integration externally when jbang is running with lower version.

or at least help with info to user on what is happening.

### PR DESCRIPTION
**Pull request by quintesse**
Fixes #1084

### CODE REVIEW

**Comment by quintesse** [comment]
Btw @maxandersen , I don't know if the new code (since the last big refactor) also fixes this issue: https://github.com/jbangdev/jbang/issues/1143 , but the issue isn't very clear so I'm not sure really how to test it. Perhaps you can take a look? Or come up with a better test/description?

**Comment by maxandersen** [comment]
Nice! Is it so it *always* runs externally or you think we can try be smart only do it when needed ?

**Comment by quintesse** [comment]
As the commit message explains, we're smart about it 🙂 

> Checks if the requested Java version is the same as the one JBang is
using and if not it will start a sub process to handle the integration
with the correct JDK.

**Comment by maxandersen** [comment]
this is brilliant fix - opens up for also run it when/if we native compile jbang!

about #1143 is not solved nor related to this afaics. 
If you take the  command in the issue and run it gives same error.

**Review by maxandersen — CHANGES_REQUESTED** [review]
please rebase it and we can happily merge it!

**Comment by quintesse** [comment]
Rebased.

**Comment by maxandersen** [comment]
Build error?

**Comment by quintesse** [comment]
Sorry, forgot to push :-)

**Pull request merged**
