### PR TITLE
issue #1531

### PR DESCRIPTION
**Pull request by kanha-gupta**
Bug fix
-Build was successful
-native command would work now

https://github.com/jbangdev/jbang/issues/1531

### CODE REVIEW

**Review by quintesse — COMMENTED** [review]
LGTM

**Review by quintesse — APPROVED** [review]

**Comment by quintesse** [comment]
To be completely perfect and ready to merge, could you perhaps change the wording of your commit to something like:

> fix: Alias command now properly sets nativeImage
>
> fixes #1531

and repush? (using --force to overwrite your previous commit)

**Comment by kanha-gupta** [comment]
@quintesse Please check, i've edited commit message.

**Comment by quintesse** [comment]
Perfect, thanks @kanha-gupta !

**Pull request merged**
