### PR TITLE
chore: Add JReleaser configuration & templates

### PR DESCRIPTION
**Pull request by aalmiray**
Initial JReleaser configuration.

### CODE REVIEW

**Comment by aalmiray** [comment]
Don't forget to define environment variables.

JRELEASER_PROJECT_VERSION
JRELEASER_GITHUB_TOKEN

**Comment by aalmiray** [comment]
Requires  https://github.com/jreleaser/jreleaser/commit/bbf8076ce9fb947ce79a88a94ba394b7e355201c or later as that enables:

 - copyright field on project
 - custom output directory when running on CLI
 - updates to chocolatey templates 
 - dryrun = true skips validation of secrets

**Comment by maxandersen** [comment]
things missing so i dont have to re-remember this everytime :

- can't seem to customize sdkman message with proper url
- can't grok what chocolatey packager actually do; docs say need to use CI - which ci?
- snap doesn't seem to work with build happening outside snap ci ?

**Comment by aalmiray** [comment]
- custom sdkman url: it's taken directly from the releaser's "release notes" url. Is not customizable at the moment.
- chocolatey CI: the idea is to follow the same setup JBang has at the moment, however the JReleaser templates do not provide starting files at the moment.
- local snap build: it used to work a couple of releases ago, perhaps I broke it.

**Pull request merged**
