### PR TITLE
Add support for trusted sources

### LINKED ISSUE #116: basic error info not printed unless --verbose
in exit handler we no longer print actual info error message unless the exceptoin has a underlying cause. should just always print.﻿

### PR DESCRIPTION
**Pull request by maxandersen**
Why:

 * @gunnarmorling rickroll https://twitter.com/gunnarmorling/status/1267033700031778816
   made it clear it would be good if could add basic protection to not run arbitrary code
   on the internet.

This change addreses the need by:

 * fix bug where error info not printed
 * before fetching url the url gets validated against trusted domains.
 * trusted domains are a list of patterns, if a match is found it is allowed;
   otherwise not.
 * if url not found jbang will print out instructions on how to add trust for that url.

Fixes #116, #113

### CODE REVIEW

**Comment by gunnarmorling** [comment]
So "trusted domain" made me first think it's about, well, domains, only.
Whereas it seems I also can decide to trust a specific sub-path only, like
https://gist.github.com/gunnarmorling/*, correct? If so, "trusted sources"
or similar might perhaps be less confusing?

>

**Comment by maxandersen** [comment]
trusted domain or trusted sites seem to be what vscode and browsers used so i used that but you have a point though...

**Comment by maxandersen** [comment]
there you go @gunnarmorling  :)

**Comment by gunnarmorling** [comment]
Nice! :thumbs_up:

**Pull request merged**
