### PR TITLE
fix: change kotlinc's extension to .bat on Windows

### LINKED ISSUE #1433: cannot run kotlin on Windows because wrong extension of kotlinc
**Describe the bug**
the code now will add `.exe` extension for `kotlinc`  in Windows, but the kotlin-compiler downloaded only contains `kotlinc` and `kotlinc.bat`. Therefore it should use `kotlinc.bat` in Windows, otherwise it causes exception.

**To Reproduce**
on Windows
1. `jbang init -t hello.kt hello.kt`
2. `jbang --verbose .\hello.kt`

**Expected behavior**
output Hello World
instead of 
```
[jbang] [ERROR] Cannot run program "C:\Users\...\.jbang\cache\kotlincs\1.6.10\kotlinc\bin\kotlinc.exe": CreateProcess error=2
```

**JBang version**
Paste output of `jbang version --verbose`
`[jbang] jbang version 0.97.0`

### PR DESCRIPTION
**Pull request by yeung66**
fixes #1433

### CODE REVIEW

**Review by quintesse — APPROVED** [review]
LGTM

Although I wonder if we shouldn't change it to use `Util.searchPaths()` so if it changes again in the future it will choose the correct exe/cmd/bat/ps1 automatically.

**Comment by yeung66** [comment]
> LGTM
> 
> Although I wonder if we shouldn't change it to use `Util.searchPaths()` so if it changes again in the future it will choose the correct exe/cmd/bat/ps1 automatically.

it seems a better way to decide extension for compiler, I will switch to use `Util.searchPaths()` later

**Review by quintesse — APPROVED** [review]
LGTM. Thanks and good job!

**Comment by maxandersen** [comment]
@all-contributors please add @yeung66  for code 

thanks!

**Comment by maxandersen** [comment]
https://github.com/all-contributors?type=source please add @yeung66 for code

**Comment by maxandersen** [comment]
@all-contributors please add @yeung66 for code

**Comment by yeung66** [comment]
> @maxandersen
> 
> @yeung66 already contributed before to code

it seems not to add me as contributor 🤣

**Pull request merged**
