### PR TITLE
feat: add //DESCRIPTION tag in scripts

### LINKED ISSUE #190: We should add a //DESC or //DESCRIPTION tag for scripts
This way we can extract that and use it for the "description" field in the `jbang-catalog.json` files.

Multiple tags would be joined together as a block of text.

### PR DESCRIPTION
**Pull request by jbardel**
A proposition that fixes #190.
Support of multiple tag DESCRIPTION that creates a merged description.
The description in argument has more precedence than the DESCRIPTION tag in the script.

### CODE REVIEW

**Review by quintesse — DISMISSED** [review]
LGTM.

**Comment by maxandersen** [comment]
Nice patch, I noticed a few things while testing:

- if I have no `//DESCRIPTION` I get `"description": ""` added to the .json - it shouldn't be there in that case.

- If we have multiple `//DESCRIPTION` should we not treat it as having a newline instead of just one large string ?

**Review by maxandersen — APPROVED** [review]
+1 on LGTM. I added the handling of null and multilines so can get a release out ;)

**Comment by jbardel** [comment]
Indeed, I forgot to test case with no //DESCRIPTION.

For the case with multiple descriptions, I thought about adding new line each time we get the tag, but wasn't sure it was the behavior expected.

Anyway, ty for the fix and the merge ! :D

**Comment by maxandersen** [comment]
@all-contributors please add @jbardel for code

thanks for the contribution!

**Pull request merged**
