### PR TITLE
fix: better check for String contains main method

### PR DESCRIPTION
**Pull request by tivrfoa**
Hi,

This patch fix/enhance the check that a String contains `main` method.

It is probably not exhausting, but it is much better than what I did before.

### CODE REVIEW

**Comment by quintesse** [comment]
That is indeed a lot better. Although does this match keyword being on different lines? Not main people do it but I _have_ seen things like:

```java
public static
void main(...) { ... }
```

It might be that the current regexp already matches this, but perhaps some kind of multi-line option needs to be set? I'm never sure how that works.

**Comment by tivrfoa** [comment]
> That is indeed a lot better. Although does this match keyword being on different lines? Not many people do it but I _have_ seen things like:
> 
> ```java
> public static
> void main(...) { ... }
> ```
> 
> It might be that the current regexp already matches this, but perhaps some kind of multi-line option needs to be set? I'm never sure how that works.

Hi Tako. It works. Here you can test:

ps. I spent a lot of time analyzing the pattern because I was using `matches()` instead of `find()` ... :expressionless: 😁 

```java
import java.util.regex.*;
import java.nio.charset.Charset;
import java.nio.file.*;

public class Util {
	public static final Pattern patternMainMethod = Pattern.compile(
			"^.*(public\\s+static|static\\s+public)\\s+void\\s+main\\s*\\(.*",
			Pattern.MULTILINE);

	public static boolean hasMainMethod(String content) {
		return patternMainMethod.matcher(content).find();
	}

	public static void main(String[] args) throws Exception {
		
		String content = new String(Files.readAllBytes(Paths.get("MultiLineMainMethod.java")), Charset.defaultCharset());
		assertTrue(Util.hasMainMethod(content));
		
		assertTrue(Util.hasMainMethod("public static void main("));
		assertTrue(Util.hasMainMethod("public static void main(String"));
		assertTrue(Util.hasMainMethod("    public static void main(String"));
		assertTrue(Util.hasMainMethod("class Main {public static void main(String...\n"));
		assertTrue(Util.hasMainMethod("class Main { public static void main("));
		assertTrue(Util.hasMainMethod("class Main {\tpublic static void main("));
		assertTrue(Util.hasMainMethod("class Main {\npublic static void main("));
		assertTrue(Util.hasMainMethod("class Main {\n\n    public static void main("));
		assertTrue(Util.hasMainMethod("       public   static   void   main  ("));
		assertTrue(Util.hasMainMethod("class Main {static public void main("));
		assertTrue(Util.hasMainMethod("       static   public   void   main  ( "));
		assertTrue(Util.hasMainMethod("}public static void main("));
		assertTrue(Util.hasMainMethod(";public static void main("));

		assertFalse(Util.hasMainMethod("class Main {public void main("));
		assertFalse(Util.hasMainMethod("class Main {static void main("));
		assertFalse(Util.hasMainMethod("public String helloWorld("));
	}
	
	public static boolean assertFalse(boolean b) {
		if (b) { throw new RuntimeException("Not false"); }
		return true;
	}
	public static boolean assertTrue(boolean b) {
		if (!b) { throw new RuntimeException("Not true"); }
		return true;
	}
}
```

```java
class MultiLineMainMethod {
    
    public static
	void
	main(String
	args
	[]) {
    	System.out.println("ops");
    }
}
```

**Comment by tivrfoa** [comment]
> That is indeed a lot better. Although does this match keyword being on different lines? Not many people do it but I _have_ seen things like:
> 
> ```java
> public static
> void main(...) { ... }
> ```
> 
> It might be that the current regexp already matches this, but perhaps some kind of multi-line option needs to be set? I'm never sure how that works.

@quintesse you can test using JBang 😄 

jbang https://gist.github.com/tivrfoa/b45c0c7f811ef410348590587a5797ca

**Comment by maxandersen** [comment]
looks good - covers more edge cases, still fail for some but those were also failures before. merging!

**Comment by quintesse** [comment]
> Hi Tako. It works. Here you can test:

Cool, nice work :-)

**Pull request merged**
