### PR TITLE
Be able to use Jbang while only having the script itself (zero-install)

### PR DESCRIPTION
**Pull request by quintesse**
See #219

### CODE REVIEW

**Comment by maxandersen** [comment]
What's the status now we have the stable URL?

**Comment by quintesse** [comment]
Well, in itself it's done. I just don't know what to do with the PowerShell version. It's works perfectly fine but if there isn't a way to pass arguments it's not very useful. So not sure if we should just commit it as-is and hope we come up will some brilliant solution in the future or if we should just remove the PS version. (Btw, running the PS version when you are in the PS doesn't seem slow at all, on the contrary).

**Comment by maxandersen** [comment]
didn't the approaches we discussed on chat allow passing in arguments via PS ?

**Comment by quintesse** [comment]
Ah, this one, right?

`iex "& { $(iwr https://raw.githubusercontent.com/quintesse/jbang/zero_install/src/main/scripts/jbang.ps1) } version"`

So now I remember. The reason this was still marked WiP is because I wanted to have the official `sh.jbang.dev` and `ps.jbang.dev` URLs working so I could add them to the comments in the beginning of the scripts :-)

**Comment by maxandersen** [comment]
Ah! Let me pull on DNS support again :)

**Comment by quintesse** [comment]
Manually merged. Closing.

**Pull request closed without merging**
