### PR TITLE
fix: have app install use better derived name

### LINKED ISSUE #653: auto naming of jbang install not honoring extension less naming like kubectl-example
`jbang app install https://github.com/jbangdev/k8s-cli-java/blob/jbang/kubectl-example` results in `KubectlExample` being installed.

it should be `kubectl-example` to be consistent with  https://github.com/jbangdev/jbang#extension-lessnon-java-files-for-cli-plugins

### PR DESCRIPTION
**Pull request by maxandersen**
i.e. `kubectl-example` stays `kubectl-example` not kebabified `KubectlExample`

Fixes #653

### CODE REVIEW

**Comment by maxandersen** [comment]
@quintesse changed this to use original ref as it probably have the "proper" name rather than any unkebabified file names.

**Comment by maxandersen** [comment]
some windows specific failures - investigating

**Comment by maxandersen** [comment]
> some windows specific failures - investigating

fixed - now it handles urls, linux and windows paths references.

**Review by quintesse — APPROVED** [review]
LGTM

**Pull request merged**
