### PR TITLE
test: add a test with a version range

### PR DESCRIPTION
**Pull request by jmini**
Add the example discussed in https://github.com/jbangdev/jbang/issues/1267#issuecomment-1054348159 to the test suite.

### CODE REVIEW

**Comment by jmini** [comment]
@maxandersen, @quintesse what prevents merging this?

This test represents how I am using Jbang with version ranges in the dependency declaration.
I would like to have this in the test-suite so that regressions in this area can be detected directly in the project.

**Review by quintesse — APPROVED** [review]
LGTM

**Comment by quintesse** [comment]
@jmini no particular reason, probably just busy :-)
Thanks for your PR!

**Comment by maxandersen** [comment]
its kinda accidental that this works though...I'm fine we merge it to notice it but that exact syntax isn't great to support in //DEPS style...lets see how it goes :)

**Comment by quintesse** [comment]
I agree, but it seemed a good idea to have this test, so we know if something changes and it breaks. Which doesn't have to mean we actually support it :-)

**Pull request merged**
