### PR TITLE
feat: enable -g by default + allow -g=vars,lines,source,none

### LINKED ISSUE #1478: expose/enable compile with debug
turns out debugging with jbang compiled does not work great as we dont add `-g` on javac  by default.

```
 -g                           Generate all debugging info
  -g:{lines,vars,source}       Generate only some debugging info
  -g:none                      Generate no debugging info
```

we could add `-g` in a first fix, but might wanna have a way for users to specify: `none,lines,vars,source`.

Possibly: `jbang -g=none whatever` would be sufficient....just feels `-g` is quite non-informative.

### PR DESCRIPTION
**Pull request by maxandersen**
Fixes #1478

### CODE REVIEW

**Comment by quintesse** [comment]
Looks just fine, but could we wait merging this until after the new project refactor has been merged? It's probably a lot easier to adapt this to that PR than the other way around.

**Comment by maxandersen** [comment]
> Looks just fine, but could we wait merging this until after the new project refactor has been merged? It's probably a lot easier to adapt this to that PR than the other way around.

Sure ... whats missing for that then ? :)

**Comment by fbricon** [comment]
what happens with `-g:none` and script contains `//JAVAC_OPTIONS -g`

**Comment by fbricon** [comment]
Doesn't seem to work with the CI build:

**Comment by fbricon** [comment]
Actually it works. JBang didn't know it needed to recompile the class with the new debug flags. Making a simple change in the source files invalidates the cache and it's properly recompiled with debug info

**Comment by maxandersen** [comment]
Ah. Good point about caching. 

@quintesse should we get caching to include these settings ?

**Comment by quintesse** [comment]
We probably should, yes. 👍

**Comment by quintesse** [comment]
@maxandersen I split the PR into 2 parts: 1 that simply always adds `-g` en 2 where I added `--compile-options` (alias `-C`).

Thing is adding the second part I noticed that the existing `--java-options` is plural while we only allow a single option to be passed. Which is probably wise because trying to allow multiple ones might become a quoting nightmare. But it does mean the name is not really correct.

I added the alias `-R` for `--java-options` which is what JShell uses (R for Runtime).

I wondered if in this case we should just get rid of the long option `--compile-options` and just leave `-C` and at the same time deprecate `--java-options` and prefer `-R` instead. Wdyt?

**Comment by maxandersen** [comment]
I'm not a fan of single letter only options. 

Could we have "-R", "--runtime-option", "--java-options" (the latter just for backwards compatibility)

and "-C", "--compile-option"  ?

**Comment by quintesse** [comment]
Of course!

**Comment by quintesse** [comment]
Done.

**Pull request merged**
