### PR TITLE
feat: added support for remote-file arguments

### LINKED ISSUE #1043: Generic remote-file argument support for `run`
It was a bit hard to come up with a good title, but I was basically thinking about something like this:

Imagine that you have a script that reads a local file:

```
jbang run readFile.java subdir/file.ext
```

But now imagine that you want to have it read a remote file, but the app doesn't support that.
But JBang already has all the code necessary to download and cache files locally.
So why not have some special syntax that lets JBang handle that? For example:

```
jbang run readFile.java @https://example.org/subdir/file.ext
```

We'd look for any arguments starting with `@http://` or `@https://` and replace them with paths to cached versions of those files.
To escape this we could do `@@http://`, which would then be replaced with the literal `@http://`.

### PR DESCRIPTION
**Pull request by quintesse**
Fixes #1043

### CODE REVIEW

**Comment by quintesse** [comment]
Sorry, couldn't resist, it's just oo useful a feature not to implement it :grin:

**Comment by maxandersen** [comment]
Maaaan...I agree this is such a tempting thing to do. But boy it feels wrong too :)

**Comment by quintesse** [comment]
@maxandersen the new version supports what you were looking for with `--javaagent`.
I have also changed the special character to `%`.

**Comment by maxandersen** [comment]
Interesting. Docs are out of sync?

**Comment by quintesse** [comment]
Oops, updated and extended docs

**Comment by maxandersen** [comment]
this is too good to not do.

**Pull request merged**
