### PR TITLE
support --javaagent:xyz.java

### PR DESCRIPTION
**Pull request by maxandersen**
everything is in place, javageent gets built if needed  *EXCEPT* I now realize I need a way to set
premain-class and agent-class in the manifest.

I kinda think we should have a //JAVAAGENT option which if present will search the java class for premain( and agentmain(
and set the respective class name.

### CODE REVIEW

**Comment by maxandersen** [comment]
will eventually fix #373

**Comment by maxandersen** [comment]
fyi https://docs.oracle.com/javase/9/docs/api/java/lang/instrument/package-summary.html has the various manifests an agent can set.

was thinking something like (in worst case)

//JAVAAGENT Can-Redefine-Classes Can-Retransform-Classes 

`Can-Redefine-Classes: true`
`Can-Retransform-Classes: true`
`Premain-Class` set if `premain(` exists
`Agent-Class` set if `agentmain(` exists in source
`boot-class-path` will be used for transitive dependencies

launcher-agent-class usecase not covered/handled. could be added in future.

**Review by quintesse — COMMENTED** [review]
Well I don't see anything wrong with it at least :-)

**Comment by maxandersen** [comment]
so one step closer, this works now:

```
jbang -Djul.JULTest=FINEST --javaagent=JULAgent.java JULTest.java World
```

even url fetch works

```
jbang --verbose -Djul.JULTest=FINEST --javaagent=https://github.com/jbangdev/jbang/blob/agents/itests/JULAgent.java JULTest.java World
```

**Comment by maxandersen** [comment]
things still missing:

- passing of options.
- custom values for Can-* options
- multiple agents

**Comment by maxandersen** [comment]
passing of options.
custom values for Can-* options
multiple agents

now all possible.

**Comment by maxandersen** [comment]
merged with fix commit mesage.

**Pull request closed without merging**
