### PR TITLE
refactor: turned `isRunCommand` into `isMainRequired`

### PR DESCRIPTION
**Pull request by andreaTP**
As requested by @quintesse :
https://github.com/jbangdev/jbang/pull/1355#pullrequestreview-958936848

### CODE REVIEW

**Review by quintesse — DISMISSED** [review]
LGTM! Thanks @andreaTP

**Comment by quintesse** [comment]
Well perhaps one small request: could you re-push with a better title? Eg, something like "refactor: turned `isRunCommand` into `isMainRequired`"

**Comment by andreaTP** [comment]
sure, done 👍

**Review by quintesse — APPROVED** [review]
Perfect!

**Pull request merged**
