### PR TITLE
Fix edit

### PR DESCRIPTION
**Pull request by ssaarinen**
Noticed that Init command used deprecated version of edit on console output.

### CODE REVIEW

**Comment by ssaarinen** [comment]
This sees weird as Spotless fails on Alias.java that I did not change. It did so on my Win machine as well but spotlessApply did not cause any changes but after that spotlessCheck succeeded. Had to force spotless to use UNIX EOL though as otherwise spotlessApply would have changed those.

**Comment by maxandersen** [comment]
thanks @ssaarinen ! 

@all-contributors please add ssaarinen for bug

**Comment by maxandersen** [comment]
had to revert the lineendings setting as that is causing conflicts in build. added gitattributes to force use of LF instead of CRLF.

**Comment by ssaarinen** [comment]
I think that's better as spotless has support for it as well 👍

**Pull request merged**
