### PR TITLE
Fixes some typos in readme.adoc

### PR DESCRIPTION
**Pull request by zakkak**

### CODE REVIEW

**Comment by maxandersen** [comment]
thank you!

**Comment by maxandersen** [comment]
whoops closed before merging..done ;)

**Comment by zakkak** [comment]
@maxandersen are you sure you merged this? It doesn't look so :)

**Comment by maxandersen** [comment]
thats what I get for merging PRs too late in the day. now it should be in!

**Comment by maxandersen** [comment]
thanks for noticing @zakkak !

**Pull request merged**
