### PR TITLE
feat: minimal jitpack and //REPOS support in edit/live mode

### PR DESCRIPTION
**Pull request by rpardini**
Minimal patch; DependencyUtils.resolveDependencies() needs a bigger refactor.

### CODE REVIEW

**Comment by rpardini** [comment]
Hmm. I meant //REPOS support, not //SOURCES.

**Comment by maxandersen** [comment]
Nice - can't believe We missed that! That explains a few weird errors in IntelliJ I had but worked fine in vscode/eclipse :)

Any chance you could expand tests in TestEdit to include one for this scenario ?

**Comment by rpardini** [comment]
There you go. Dunno which jitpack dep to use for test, just used one of mine.
It shouldn't actually resolve during tests (except for string-based conversion) so shouldn't break in case it goes away.

**Comment by maxandersen** [comment]
Perfect! Thank you @rpardini !

@all-contributors please add @rpardini for code

**Pull request merged**
