### PR TITLE
feat: Startup scripts now use User-Agent header for downloads

### PR DESCRIPTION
**Pull request by quintesse**
Has to be applied after https://github.com/jbangdev/jbang/pull/1036

### CODE REVIEW

**Comment by maxandersen** [comment]
Wont These be problematic when using sh.jbang.dev and ps1.jbang.dev for direct download using main github content ? The version wont be extracted…

**Comment by maxandersen** [comment]
this fix result in all scripts being missing from the archive so rolling it back to make working release as it breaks curl.

**Comment by quintesse** [comment]
That's weird, it seemed to work locally. Have any idea why it falls?

**Comment by maxandersen** [comment]
the dependsOn is not working as we think it does.

See this twitter thread https://twitter.com/CedricChampeau/status/1454788194789101568 that cover some of it.

**Comment by quintesse** [comment]
I've added this as a Maybe to the 1.0 roadmap. Not essential but I think it would be good to have a proper User-Agent from 1.0 onwards.

**Comment by quintesse** [comment]
Oops, this was the PR, removing again :-)

**Pull request merged**
