### PR TITLE
Update Quarkus and Picocli dependencies

### PR DESCRIPTION
**Pull request by jarryDk**
Get the newest version of Quarkus when using template qmetrics and qrest.

Align the use of Picocli to be 4.6.3 in the code base, test, template and documentation.

### CODE REVIEW

**Comment by maxandersen** [comment]
thanks - you didn't have to update the various tests using picocli as good to verify older struff still works - but minor :) lets see if it builds and i'll merge.

**Comment by jarryDk** [comment]
Same story as with Quarkus - when to start using JDK 11?

```
/home/runner/work/jbang/jbang/qcli.java:13: error: cannot access QuarkusMain
import io.quarkus.runtime.annotations.QuarkusMain;
                                     ^
  bad class file: /home/runner/.m2/repository/io/quarkus/quarkus-core/2.11.2.Final/quarkus-core-2.11.2.Final.jar(io/quarkus/runtime/annotations/QuarkusMain.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
Error:  [ERROR] Error during compile
[jbang] Run with --verbose for more details
Error: Process completed with exit code 1.
```

**Comment by maxandersen** [comment]
> Same story as with Quarkus - when to start using JDK 11?

not anytime soon as jbang do not need it.

I've pushed fix so quarkus templates will require java 11 or higher.

that should fix the problem.

**Comment by maxandersen** [comment]
@all-contributors please add @jarryDk  for code

**Pull request closed without merging**
