### PR TITLE
fix:  jbang edit suggests incorrect command when template renames out…

### PR DESCRIPTION
**Pull request by grumpyf0x48**
Use the first rendered file using `{baseName}` as the name to use in suggested edit command.

### CODE REVIEW

**Comment by grumpyf0x48** [comment]
Didn't add tests because i guess you don't write tests to expect JBang output.

**Comment by maxandersen** [comment]
We do. See itest folder for .feature.

**Comment by grumpyf0x48** [comment]
> We do. See itest folder for .feature.

Great ! Not seen cucumber was used there so far.

To test the change in `init` output, we need to have a template using something like `"{baseName}Test.java": "templates/..."`.

So two possibilities here:

- Such a template exists somewhere and can be used in tests: for example in jbangdev catalog (`catalog.feature` already uses this catalog)
- The template needs to be created in tests by a JBang command line

The first option makes me think that we could use JUnit templates once they are merged.

For the second option, how to create a template looking like:

```
    "junit4b": {
      "file-refs": {
        "{basename}Test.java": "templates/junit4b.java.qute"
      },
      "description": "Basic template for JUnit4 tests"
    },
```

with a JBang command line ?

**Comment by quintesse** [comment]
> how to create a template 

IIRC you can do: `jbang template add --name junit4b "{basename}Test.java=templates/junit4v.java.qute"`

**Comment by maxandersen** [comment]
@all-contributors please add @grumpyf0x48  for code

**Comment by maxandersen** [comment]
@all-contributors please add @grumpyf0x48 for code

**Pull request merged**
