### PR TITLE
Fix watchservice take

### PR DESCRIPTION
**Pull request by dem2k**
watchservice.take methode never comes back. the process should be interrupted hard.

### CODE REVIEW

**Comment by maxandersen** [comment]
educate me here - I can see its not great; but what is actually failing for you ?

**Comment by dem2k** [comment]
I can show you better:  https://www.dropbox.com/sh/7u7x3a11b5aysee/AADX3LkbS213GYean6DG_ASIa?dl=0

**Comment by maxandersen** [comment]
great videos - now it makes sense. yeah - needs fixing ;)

**Comment by maxandersen** [comment]
looks good! merging!

**Comment by maxandersen** [comment]
Had to revert this as it assumes the edit process runs forever. that is not the case when you are using launchers as used by code, idea or emacs -nw

**Pull request merged**
