### PR TITLE
fix: remove unnecessary quotations for java binary

### LINKED ISSUE #1412: `jbang.cmd` broken after #1389 when `JAVA_HOME` has spaces
**Describe the bug**
`jbang.cmd` broken after #1389 when `JAVA_HOME` has spaces

**To Reproduce**
1. Install `jbang` version `0.96.0` on a Windows 10 host using `chocolatey`. 
```ps1
choco install jbang
```
2. execute `jbang --version`
3. See error
```
'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Expected behavior**
`jbang` should work fine on Windows 10 host 

**JBang version**
`0.96.0`

**Additional context**

- Host version
```
PS C:\WINDOWS\system32> [environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19044  0
```

- Potentially impacted community

Anyone who has installed `jbang` and the `jdk` using [`chocolatey`](https://chocolatey.org/), given that the installation script uses `jbang.cmd` as the `BinFile` 

image

And the `jdk` usually gets installed in the `C:\Program Files` dir, which has a space. 

image

### PR DESCRIPTION
**Pull request by garodriguezlp**
fix #1412

### CODE REVIEW

**Comment by quintesse** [comment]
Thank you for your PR @garodriguezlp ! But I wanted to ask if you can also test the PowerShell script, because I imagine it could have the same problem.

**Comment by garodriguezlp** [comment]
> Thank you for your PR @garodriguezlp ! But I wanted to ask if you can also test the PowerShell script, because I imagine it could have the same problem.

`PowerShell` script working fine for me. But I'm experiencing this weird behavior; not sure if it's a bug or a bad usage. 
image

I'm doing more research and comparing with previous versions; I'll create the bug if I can verify this doesn't happen in previous versions. Although, I'd appreciate any thought or guidance about it.

Thanks!

**Comment by quintesse** [comment]
Your fix was _almost_ correct. It was indeed an issue of excessive quotes, but it was a `set` on another line that was mistakenly adding quotes to the actual value which was not correct. I've updated your PR and will merge it once the tests pass.

**Review by quintesse — APPROVED** [review]

**Comment by quintesse** [comment]
Merged. Thanks a lot @garodriguezlp !

**Pull request merged**
