### PR TITLE
feat: Enabled the usage of existing JDK installations

### PR DESCRIPTION
**Pull request by quintesse**
Right now we have support for using (not managing!) SDKMAN and Scoop installations.

### CODE REVIEW

**Comment by maxandersen** [comment]
hmm - how is that supposed to work? 
I'll some convincing to add this :)

How does version comparison work? Which variation of sdk and scoops installs do we look at/consider?

**Comment by quintesse** [comment]
It's just "in-order". JBang's JDKs come first. If a requested version is not available it will try the next provider, eg SDKMAN. If it exists it uses it, if not it will fall back to installing the JDK using JBang, as before. And there's no version comparison, a provider either has a version X (major, eg 10, 11, 14, etc) or it doesn't.

**Comment by quintesse** [comment]
Ok @maxandersen , this now has a `jdkproviders.enabled` config option that you can set to `true` to tell JBang to use sdkman/scoop-installed JDKs. By default this is set to `false`. It would still be nice to see if we can add support for "alternatives" as well, although it might actually be easier to just look at a specific set of standard folders where Linux/Mac OSses tend to install their JDKs.

**Comment by quintesse** [comment]
Ok, all tests pass again. This should finally be ready for merging.

**Comment by quintesse** [comment]
The config option has now be turned into a hidden flag, `--jdk-providers`, on `run` and `build` that takes a comma-separated list of provider names (order matters). The currently supported names are: path, javahome, jbang, sdkman and scoop. By default the value for this flag is "path,javahome,jbang". You can of course still set the value using config options, but there are now named: `run.jdkproviders` and `build.jdkproviders`.

**Comment by maxandersen** [comment]
Should it not be `javahome,path,jbang` by default?

**Comment by quintesse** [comment]
> Should it not be `javahome,path,jbang` by default?

Yes, it is, I just wrote it down wrong in the comment. I updated it.

**Comment by maxandersen** [comment]
trying this out and it does not seem to work for me: `jbang jdk --jdk-providers=sdkman list` gives:

```
[jbang] jbang version 0.101.0.13
[jbang] [ERROR] No providers could be initialized. Aborting.
dev.jbang.cli.ExitException: No providers could be initialized. Aborting.
	at dev.jbang.net.JdkManager.initProvidersByName(JdkManager.java:75)
	at dev.jbang.cli.JdkProvidersMixin.initJdkProviders(JdkProvidersMixin.java:17)
	at dev.jbang.cli.Jdk.list(Jdk.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1972)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:147)
	at dev.jbang.cli.JBang$3.handle(JBang.java:142)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

wondering if it fails because i don't actually have any sdkman java folder yet?

Beyond that we should have some basic docs for how to use this.

**Comment by maxandersen** [comment]
also...should `jbang jdk --jdk-providers=path list` technically not list *something* ?

**Comment by maxandersen** [comment]
so yes, issue with sdkman was that i had no jdks installed yet. that shouldn't fail IMO.

That said now I installed 2 java 17's and I get:

```
jbang jdk --verbose --jdk-providers=sdkman list --show-details
[jbang] jbang version 0.101.0.13
Installed JDKs (<=default):
   17 (17.0.5, sdkman, 17.0.5-amzn-sdkman, /Users/manderse/.sdkman/candidates/java/17.0.5-amzn)
   17 (17.0.5, sdkman, 22.3.r17-grl-sdkman, /Users/manderse/.sdkman/candidates/java/22.3.r17-grl)
```

how do I as a user know which is picked when I use `//JAVA 17` ?

**Comment by maxandersen** [comment]
`jbang jdk install 17` complains about java 17 already being installed...surprised me. turns out its because sdkman installed it in path. Maybe have message state which java 17 it is considering.

**Comment by maxandersen** [comment]
this might be expected but seems inconsistent to me somehow:

```
jbang jdk list --show-details
Installed JDKs (<=default):
   8 (1.8.0_352, jbang, 8-jbang, /Users/manderse/.jbang/cache/jdks/8)
   11 (11.0.17, jbang, 11-jbang, /Users/manderse/.jbang/cache/jdks/11)
   17 (17.0.4.1, jbang, 17-jbang, /Users/manderse/.jbang/cache/jdks/17) <
❯ jbang jdk jdk-env
Unmatched argument at index 1: 'jdk-env'
Did you mean: java-env?
❯ jbang jdk java-env
export PATH="/Users/manderse/.jbang/currentjdk/bin:$PATH"
export JAVA_HOME="/Users/manderse/.jbang/currentjdk"
# Run this command to configure your shell:
# eval $(jbang jdk java-env)
```

why is default java-env using a path not listed in available JVMs?

**Comment by maxandersen** [comment]
another quirk:

```
jbang jdk --verbose --jdk-providers=path,sdkman java-env
[jbang] jbang version 0.101.0.13
[jbang] No default JDK set, use 'jbang jdk default <version>' to set one.
[jbang] [ERROR] JDK null is not installed
dev.jbang.cli.ExitException: JDK null is not installed
	at dev.jbang.cli.Jdk.javaEnv(Jdk.java:183)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1972)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:147)
	at dev.jbang.cli.JBang$3.handle(JBang.java:142)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
```

might be because i have java11 in path but jbang seem to want a release file?

```
 jbang jdk --verbose --jdk-providers=path,sdkman list --show-details
[jbang] jbang version 0.101.0.13
[jbang] Unable to read 'release' file in path: /usr
Installed JDKs (<=default):
   17 (17.0.5, sdkman, 22.3.r17-grl-sdkman, /Users/manderse/.sdkman/candidates/java/22.3.r17-grl)
```

**Comment by quintesse** [comment]
> also...should jbang jdk --jdk-providers=path list technically not list something ?

If you don't have any `javac` in your path it won't return any results, no. In my case it returns "8".

> so yes, issue with sdkman was that i had no jdks installed yet. that shouldn't fail IMO.

When you say it shouldn't fail you refer to the exception? That should indeed just be a simple error message. Or are you saying it should do something else?

> why is default java-env using a path not listed in available JVMs?

It's because you were testing a slightly older version that showed "real" paths, I changed that and now it shows the original paths which can be symbolic links. This should make it more obvious what each JDK is pointing to.

> Maybe have message state which java 17 it is considering.

You mean something like: "Java 17 is already installed: /home/user/blah/blah/jdk17", or perhaps with the full details like: "Java 17 is already installed: 17 (17.0.4.1, jbang, 17-jbang, /Users/manderse/.jbang/cache/jdks/17)"?

> might be because i have java11 in path but jbang seem to want a release file?

That's the first unexpected situation. I'll need to look into that. And yes, all JDKs need a "release" file in their root. So far luckily I haven't found any example of a distribution that removes it. But it's how JBang now detects what version a JDK is, instead of running `java -version` and parsing its output.

**Comment by maxandersen** [comment]
> > also...should jbang jdk --jdk-providers=path list technically not list something ?
> 
> If you don't have any `javac` in your path it won't return any results, no. In my case it returns "8".

I have `javac` in my path:

```
❯ jbang jdk --jdk-providers=path list
No JDKs installed
❯ jbang jdk --jdk-providers=path list
❯ which java
/usr/bin/java
❯ which javac
/usr/bin/javac
```

and both current and this PR have jbang working without downloading additional jdks so it does find it.

> > so yes, issue with sdkman was that i had no jdks installed yet. that shouldn't fail IMO.
> 
> When you say it shouldn't fail you refer to the exception? That should indeed just be a simple error message. Or are you saying it should do something else?

I'm saying that if I have no java installed in my sdkman then it should not fail with an exception; it should just report 0 found jdks in sdkman.
 
> > why is default java-env using a path not listed in available JVMs?
> 
> It's because you were testing a slightly older version that showed "real" paths, I changed that and now it shows the original paths which can be symbolic links. This should make it more obvious what each JDK is pointing to.

I'm using jbang built from this PR. It still shows using different paths:

```
 jbang jdk java-env
export PATH="/Users/manderse/.jbang/currentjdk/bin:$PATH"
export JAVA_HOME="/Users/manderse/.jbang/currentjdk"
# Run this command to configure your shell:
# eval $(jbang jdk java-env)
❯ jbang jdk list --show-details
Installed JDKs (<=default):
   8 (1.8.0_352, jbang, 8-jbang, /Users/manderse/.jbang/cache/jdks/8)
   11 (11.0.17, jbang, 11-jbang, /Users/manderse/.jbang/cache/jdks/11)
   17 (17.0.4.1, jbang, 17-jbang, /Users/manderse/.jbang/cache/jdks/17) <
```

> > Maybe have message state which java 17 it is considering.
> 
> You mean something like: "Java 17 is already installed: /home/user/blah/blah/jdk17", or perhaps with the full details like: "Java 17 is already installed: 17 (17.0.4.1, jbang, 17-jbang, /Users/manderse/.jbang/cache/jdks/17)"?

yes - that would be great.

> > might be because i have java11 in path but jbang seem to want a release file?
> 
> That's the first unexpected situation. I'll need to look into that. And yes, all JDKs need a "release" file in their root. So far luckily I haven't found any example of a distribution that removes it. But it's how JBang now detects what version a JDK is, instead of running `java -version` and parsing its output.

i believe that for systems where java is on path like osx and if installed jdk via package manager you cant rely on release being in parent dir. And thus should still call out to `-version` as fallback.

**Comment by quintesse** [comment]
```
❯ which javac
/usr/bin/javac
```

Can you check if that's a symlink? Or are they scripts that locate and execute the actual binary?

**Comment by maxandersen** [comment]
```
 bat /usr/bin/javac

       │ File: /usr/bin/javac   <BINARY>

❯ ls -l /usr/bin/javac
.rwxr-xr-x 168k root 18 Out 14:36 /usr/bin/javac
```

its a binary.

**Comment by maxandersen** [comment]
more specifically its a adoptopenjdk version:

```
javac --version
javac 11.0.11
❯ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

**Comment by maxandersen** [comment]
if i empty sdkman/candidates/java and unset java_home these should give same messages:

```
 jbang jdk --jdk-providers=sdkman list --show-details
[jbang] [ERROR] No providers could be initialized. Aborting.
[jbang] Run with --verbose for more details
❯ jbang jdk --jdk-providers=sdkman,javahome list --show-details
No JDKs installed
```

**Comment by maxandersen** [comment]
i think we should include the ID in default jdk list:


```
jbang jdk --jdk-providers=sdkman list --show-details
Installed JDKs (<=default):
   17 (17.0.5, sdkman, 22.3.r17-grl-sdkman, /Users/manderse/.sdkman/candidates/java/22.3.r17-grl)
   17 (17.0.5, sdkman, current-sdkman, /Users/manderse/.sdkman/candidates/java/current)
❯ jbang jdk --jdk-providers=sdkman list
Installed JDKs (<=default):
   17 (17.0.5)
❯ jbang jdk --jdk-providers=sdkman list
Installed JDKs (<=default):
   17 (17.0.5)
```
would expect it to show current-sdkman or 22.3.r17-grl-sdkman

**Comment by maxandersen** [comment]
tried install with sdkman:

```
jbang jdk --jdk-providers=sdkman --verbose java-env 12.0-sdkman
JAVA_HOME is set but does not seem to point to a valid Java JDK
[jbang] jbang version 0.101.0.25
[jbang] [ERROR] No providers could be initialized. Aborting.
dev.jbang.cli.ExitException: No providers could be initialized. Aborting.
	at dev.jbang.net.JdkManager.initProvidersByName(JdkManager.java:86)
	at dev.jbang.cli.JdkProvidersMixin.initJdkProviders(JdkProvidersMixin.java:17)
	at dev.jbang.cli.Jdk.javaEnv(Jdk.java:181)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1972)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at dev.jbang.cli.JBang$3.handle(JBang.java:147)
	at dev.jbang.cli.JBang$3.handle(JBang.java:142)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at dev.jbang.Main.main(Main.java:14)
[jbang] If you believe this a bug in jbang, open an issue at https://github.com/jbangdev/jbang/issues
❯ jbang jdk --jdk-providers=sdkman java-env 12.0-sdkman
JAVA_HOME is set but does not seem to point to a valid Java JDK
[jbang] [ERROR] No providers could be initialized. Aborting.
[jbang] Run with --verbose for more details
```

**Comment by quintesse** [comment]
> tried install with sdkman:

And you were using the latest version? Because I get a different error:

```
$ jbang jdk --jdk-providers=sdkman --verbose java-env 123-sdkman
[jbang] jbang version 0.101.0.25
[jbang] [ERROR] JDK id is not available for installation: 123-sdkman
```

which is correct.

If I use an existing id it works fine:

```
$ jbang jdk --jdk-providers=sdkman --verbose java-env 11.0.12-open-sdkman
[jbang] jbang version 0.101.0.25
[jbang] Using JDK: 11 (11.0.12, 11.0.12-open-sdkman, /home/tschotan/.sdkman/candidates/java/11.0.12-open)
export PATH="/home/tschotan/.sdkman/candidates/java/11.0.12-open/bin:$PATH"
export JAVA_HOME="/home/tschotan/.sdkman/candidates/java/11.0.12-open"
# Run this command to configure your shell:
# eval $(jbang jdk java-env 11.0.12-open-sdkman)
```

**Comment by maxandersen** [comment]
Ah. It's not telling sdkman to install it. Gotcha. 

Maybe respond with an error stating the id is not found but you can install generic java using numbers or otherwise see available jdks using jdk list?

**Comment by quintesse** [comment]
> Ah. It's not telling sdkman to install it. Gotcha.

No, although that's definitely technically possible, the provider would "just" need to implement the `install()` method, but I decided that was just too much for now. So for any 3rd party providers the user need to use the appropriate 3rd party install mechanism.

> Maybe respond with an error stating the id is not found but you can install generic java using numbers or otherwise see available jdks using jdk list?

Done.

**Comment by maxandersen** [comment]
although this does not set working java_home:

```
 jbang jdk --jdk-providers=path java-env
export PATH="/usr/bin:$PATH"
export JAVA_HOME="/usr"
# Run this command to configure your shell:
# eval $(jbang jdk java-env)
```

I'm going to merge it with that as a known limitation we can improve on - as its a rather obscure option atm :)

**Pull request merged**
