### PR TITLE
fix: Invalid comment in jbang.cmd

### PR DESCRIPTION
**Pull request by quintesse**
Small but very wrong typo

### CODE REVIEW

**Comment by quintesse** [comment]
Still can't merge stuff by myself @maxandersen , will wait for your review :-)

**Review by maxandersen — APPROVED** [review]
lgtm - surprised how that could pass integration tests?

**Review by maxandersen — COMMENTED** [review]
lgtm

**Comment by quintesse** [comment]
> how that could pass integration tests?

Because errors in .cmd files are not fatal, so it's just this extra message that appears in the output

**Pull request merged**
