### PR TITLE
Added `aarch64` to list of supported architectures

### LINKED ISSUE #226: Java installations not handling aarch64
The Java version downloaded for jbang is not the right one for aarch64:

```
Downloading JDK 11. Be patient, this can take several minutes...
Installing JDK 11...
/home/g/.qollider/jbang/bin/jbang: line 126: /home/g/.jbang/cache/jdks/11/bin/java: cannot execute binary file: Exec format error
```

### PR DESCRIPTION
**Pull request by quintesse**
Fixes #226

### CODE REVIEW

**Comment by quintesse** [comment]
@galderz any chance that you could test if this PR fixes things for you?

**Comment by maxandersen** [comment]
looks innocent enough to merge :)

**Comment by galderz** [comment]
Testing...

**Comment by galderz** [comment]
JDKs dowloaded but not yet fully working, see #243.

**Pull request merged**
