### PR TITLE
fix: do not fail on unrecognized OS like arm64 for new macs. should at least try run located java. Fixes #650

### LINKED ISSUE #650: Add support for macOS arm64
image

### PR DESCRIPTION
**Pull request by maxandersen**

### CODE REVIEW

**Comment by maxandersen** [comment]
idea for this is that jbang wont fail early on unknown OS but at least go use java available in path.

@quintesse something I might have missed ?

**Comment by quintesse** [comment]
We will have to fix the startup scripts as well, eg: https://github.com/jbangdev/jbang/blob/master/src/main/scripts/jbang#L51

**Comment by quintesse** [comment]
I think the best thing to do there is to move the `exit` to the part of the code where we try to download the JDK. If in that part `$os == ""` we can just exit. Perhaps with an extra message like "No Java found and OS is not supported for automatic download".

**Comment by maxandersen** [comment]
Good catch. Is that a change you can add to this branch/pr or want me to recall my bad scripting skills? :)

**Comment by quintesse** [comment]
Added my own branch becuase I didn't have the rights to update yours: https://github.com/jbangdev/jbang/pull/657

**Comment by maxandersen** [comment]
ack - thought you already had push access; my bad - fixed now so don't push to origin by accident - now it won't fail ;)

**Comment by maxandersen** [comment]
closing.

**Comment by quintesse** [comment]
> fixed now so don't push to origin by accident

Have you turned off pushing to "master"? That at least makes things safer. Accidentally overwriting a branch is most likely less of a problem than overwriting master :-)

**Comment by maxandersen** [comment]
> Have you turned off pushing to "master"? That at least makes things safer. Accidentally overwriting a branch is most likely less of a problem than overwriting master :-)

that would require some bot to do merges to master? (but no, haven't turned off master pushes)

**Comment by quintesse** [comment]
The idea is that all changes are done using PRs, no direct pushes to master ever.
(As admin you can always turn it off temporarily if you really need to push, for example to do a force-push to remove sensitive information)

**Comment by maxandersen** [comment]
So when/what does the pushes ?
I'm all for enabling it - just haven't tried it yet so not sure what to enable on GitHub to make it happe.

**Comment by quintesse** [comment]
There are no pushes to master, only PRs that get merged. You can only do pushes to branches.

**Comment by quintesse** [comment]
You can set that protection here: https://github.com/jbangdev/jbang//settings/branch_protection_rules/new (that should be the correct URL, can't test it cause I don't have the rights). You set the name to "master", enable any other options you like (by default it only protects against force pushes from non-admins) and hit Create.

**Comment by maxandersen** [comment]
Okey. Enabled :)

**Pull request closed without merging**
