### PR TITLE
Install wrapper

### PR DESCRIPTION
**Pull request by quintesse**
This copies the startup files and the JAR file to either the current directory or the specified one.

### CODE REVIEW

**Comment by quintesse** [comment]
One thing, this leaves the original names intact. I'm not sure if we should rename them to `jbangw` and `jbang.cmd` instead. It would at least be consistent with what everybody else is doing. Wdyt?

**Review by maxandersen — CHANGES_REQUESTED** [review]
this looks good - could you add a basic karate test of install and run that ./jbang from that directory ?

**Comment by maxandersen** [comment]
> One thing, this leaves the original names intact. I'm not sure if we should rename them to `jbangw` and `jbang.cmd` instead. It would at least be consistent with what everybody else is doing. Wdyt?

you mean `jbangw` and `jbangw.cmd` ? no - i don't think thats valid in this case as its literally still jbang...its just installed where it picks up jar differently.

**Comment by quintesse** [comment]
Tests added!

**Pull request merged**
