### PR TITLE
chore: made `version --verbose` more verbose

### PR DESCRIPTION
**Pull request by quintesse**
Added a couple of more informational lines that can help us debug issues that people might have with JBang.

### CODE REVIEW

**Review by maxandersen — APPROVED** [review]

**Comment by maxandersen** [comment]
@quintesse seems like integrations tests is broken because of this. probably more content than expected?

**Comment by quintesse** [comment]
> @quintesse seems like integrations tests is broken because of this. probably more content than expected?

No, the error seems to be:

```
Error:  [ERROR] Could not resolve dependencies: Failed to collect dependencies at com.github.intuit.karate:karate-netty:jar:e2882c4
```

Let's re-run and see if that fixes things....

**Comment by maxandersen** [comment]
Ohh.. Missed that:/

**Comment by quintesse** [comment]
It built correctly this time

**Review by maxandersen — APPROVED** [review]

**Pull request merged**
